builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
archives:
  - name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    replacements:
      386: i386
      amd64: x86_64
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  -
    package_name: metrics
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://github.com/umputun/metrics
    maintainer: Umputun <umputun@gmail.com>
    description: metrics service with the real-time aggregation
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1
