### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
"name": "test", "time_stamp": "2022-11-15T15:04:05Z", "value": 5
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "test", "time_stamp": "2022-11-15T15:04:05Z", "value": 9
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "test2", "time_stamp": "2022-11-15T21:04:05Z", "value": 1
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "test2", "time_stamp": "2022-11-15T11:04:05Z", "value": 2
}

### Delete metric
DELETE localhost:8080/metric?name=test
Authorization: Basic admin Lapatusik

### Get list of metrics
GET localhost:8080/get-metrics-list

### Get metric data
POST localhost:8080/get-metric

{"name": "test", "from": "2022-11-15T14:04:05Z", "to": "2022-11-15T16:04:05Z", "interval": "30m"}

### Get all metrics data
POST localhost:8080/get-metrics

{"from": "2022-11-15T10:04:05Z", "to": "2022-11-15T23:04:05Z", "interval": "30m"}

### Get all metrics data
POST localhost:8080/get-metrics

{"from": "2022-11-15T10:04:05Z", "to": "2022-11-15T23:04:05Z", "interval": "12h"}

### Get all metrics data
POST localhost:8080/get-metrics

{"from": "2022-11-15T10:04:05Z", "to": "2022-11-15T23:04:05Z", "interval": "24h"}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T01:04:05Z", "value": 1
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T01:14:05Z", "value": 2
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T01:24:05Z", "value": 3
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T01:44:05Z", "value": 4
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T02:44:05Z", "value": 5
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T03:44:05Z", "value": 6
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T04:44:05Z", "value": 7
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T05:44:05Z", "value": 8
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T06:44:05Z", "value": 9
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T08:44:05Z", "value": 1
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T09:44:05Z", "value": 3
}

### Post metric
POST localhost:8080/metric
Authorization: Basic admin Lapatusik
Content-Type: application/json

{
  "name": "file_1", "time_stamp": "2022-12-11T10:44:05Z", "value": 3
}